### ISSUE TITLE
Covid19 Todesfaelle in WHO

### ISSUE THREAD

**Issue by dkobak** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#1]
I am trying to understand the German Covid-19 deaths data in the WHO dataset (https://covid19.who.int/data). WHO dataset contains daily data on Covid deaths across many countries. The German data there is different from the RKI data by "Meldedatum": it appears to be shifted by around 2 weeks earlier: 

![germany-daily-who-rki](https://user-images.githubusercontent.com/8970231/223179738-9ff74ad9-e2c2-4003-be07-7c8aad1d89d7.png)

Curiously, the total cumulative sum is the same.

Furthermore, I compared both datasets with the RKI deaths data by "Sterbedatum" (which is only available with weekly resolution). The WHO data appears to be shifted by around 1 week earlier compared to the RKI-Sterbedatum, which does not make any sense to me.

![germany-rki-who](https://user-images.githubusercontent.com/8970231/223179846-3d32694c-29c0-4eae-8109-1576021a527f.png)

I have tried reaching out to WHO to find out the exact source of German data that they use, but unfortunately did not receive any reply. So I thought maybe somebody at RKI knows the origin of the WHO data.

**Comment by HannesWuensche** [comment]
He @dkobak,

thank you for reaching out to us about the matter. 
The problem you refer to is described by the [WHO](https://covid19.who.int/data):

> Caution must be taken when interpreting all data presented, and differences between information products published by WHO, national public health authorities, and other sources using different inclusion criteria and different data cut-off times are to be expected.

In the "Data Sources" section I could not find any explicit reference on how the German data was collected. I forwarded the question to my colleges in charge of the German Covid-19 deaths. Accordingly, we will try to reach out to WHO too. 

Some general remarks: 
- the variable "Meldedatum" refers to the date were the regional health department defines a case as COVID-19 case. It has nothing to do with the date of death ("Sterbedatum") 
- besides the "Meldedatum" and the "Sterbedatum", the "Berichtsdatum" makes the date, where the RKI reports a COVID-19 case or cases als well es COVID-19 deaths.

Best regards
@HannesWuensche 
for the Team RKI | Open Data

**Comment by dkobak** [comment]
Thank you @HannesWuensche.

The blue curves in my figures above used this dataset: https://github.com/robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland/blob/main/COVID-19-Todesfaelle_Deutschland.csv, so I guess I should have named that "Berichtsdatum" instead of "Sterbedatum".

> In the "Data Sources" section I could not find any explicit reference on how the German data was collected. I forwarded the question to my colleges in charge of the German Covid-19 deaths. Accordingly, we will try to reach out to WHO too.

That would be great. I am really curious where the WHO gets the German deaths data from, and why does it differ from both RKI-Berichtsdatum and RKI-Sterbedatum. If you manage to find out anything, please let me know.
