### ISSUE TITLE
Im Update vom 3.1.24 fehlen die aktuellen Daten vom 3.1.

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#14]
Das war auch an eingen Tagen in der letzten Woche so.

**Comment by HorstErnst** [comment]
Es scheint inzwischen zur Regel zu werden, dass die Zahlen mit einem Tag Verspätung eingetragen werden.

**Comment by Anna-Lyst** [comment]
Schon seltsam - auch am heutigen 04.01.2024 lief *als einziges* (von den dreien) um 05:51 ein Pseudo-Update für die "Todesfälle in Deutschland" (nicht aber für 'Bundesländer' oder 'Altersgruppen' !!) ... und erneut fehlen darin die Daten für den aktuellen Tag !!
Wie ich schon in meiner Issue-Meldung vom 29.12. schrieb: "Eine Erklärung, was los ist, wäre nett ... immerhin arbeiten ja noch einige täglich mit diesen Daten (oder versuchen es zumindest)." Das gilt weiterhin ...

Also, liebes **RKIOpenData**-Team: wollt Ihr 'uns' nicht doch mal eine kurze Erklärung geben? Das wäre **_nett !_**
.

**Comment by HannesWuensche** [comment]
Liebe Alle,

vielen Dank für die Rückmeldungen. 
Das seit kurzem die Daten der aktuellen Berichtstage fehlen schauen wir uns derzeit an. 

Täglich wird nur die `COVID-19-Todesfaelle_Deutschland.csv` aktualisiert. Die anderen beiden Dateien im wöchentlichem Rhythmus (siehe Dokumentation). 

> Die Daten nach Bundesländern den wöchentlichen Stand Sonntag 24:00 Uhr, aller über das Meldesystem gemäß Infektionsschutzgesetz an das RKI übermittelten COVID-19-Fälle ab. Das bedeutet, dass alle bis Sonntag 24:00 Uhr von den Gesundheitsämtern über die zuständigen Landesbehörden an das RKI übermittelten COVID-19-Fälle im Datenstand enthalten sind. Die Daten werden wöchentlich vollständig neu erzeugt, dieser Datenstand ersetzt den Datenstand der Vorwoche.

Aufgrund des nach wie vor hohen Krankenstands, der Ferien und Urlaubszeit in Berlin sind wir jedoch dünn besetzt und müssen Aufgaben priorisieren. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
