### ISSUE TITLE
09.01. ohne Meldung

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#15]
Auch heute wieder: in der  COVID-19-Todesfaelle_Deutschland.csv fehlt der aktuelle Wert. Zusammen mit den Null-Meldungen von Sonntag und Montag ergibt das eine Lücke von drei Tagen.

**Comment by RKIOpenData** [comment]
Hallo @HorstErnst,

vielen Dank für den Hinweis. Wir hatten leider technische Probleme bei der Erzeugung der Daten. Jetzt sollte aber alles vollständig sein.

Beste Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by HorstErnst** [comment]
Heißt das, das nunmehr tatsächlich die Zahlen mit einem Tag Verspätung eingetragen werden? Dies war seit den Feiertagen so zu beobachten und auch heute sind ja nur die Zahlen vom 09.01. nachgetragen worden.
