### ISSUE TITLE
Todesfälle ab jetzt immer mit einem Tag Verspätung?

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#16]
Knut Perseke schrieb: "Wir hatten leider technische Probleme bei der Erzeugung der Daten. Jetzt sollte aber alles vollständig sein." Tatsächlich wurden heute (10.01.) lediglich die Todesfälle vom 09.01. nachgetragen.

Heißt das, das nunmehr tatsächlich die Zahlen mit einem Tag Verspätung eingetragen werden?

**Comment by knutator2** [comment]
Hallo @HorstErnst,

es gab leider noch ein Problem mit dem automatisierten Upload. Jetzt sind auch die Zahlen vom 10.01. eingetragen.

Beste Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by HorstErnst** [comment]
Vielen Dank!
