### ISSUE TITLE
update vom 26.1.23?

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#17]

**Comment by RKIForschungsdatenmanagement** [comment]
Hallo @Rutger265,

vielen Dank für den Hinweis, 
leider werden wir es heute nicht mehr schaffen den Fehler zu beheben, wir hoffen mit dem Update morgen die aktualisierten Daten bereit stellen zu können. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data
