### ISSUE TITLE
Keine Daten seit dem 30.07.

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#23]
Wie der Betreff schon sagt: die letzte Zahl zu den COVID-10_Todesfällen ist vom 30.07. 

Wie geht es nun weiter?

**Comment by Rutger265** [comment]
Seit zwei Tagen sind die kumulierten Daten (Fälle und Todesfälle) einen Tag verspätet.
Die neu gemeldeten Todesfälle (= Differenz der kumulierten Todesfälle) werden gar nicht mehr ausgewiesen.

**Comment by HorstErnst** [comment]
Okay, danke.
