### ISSUE TITLE
Erinnerung: Aktualisierung von diesem Repository (und vielen anderen) fehlt seit dem 22.8.!

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#24]

**Comment by RKIOpenData** [comment]
Hallo, 
vielen Dank für ihre Nachricht. Wir hatten dazu heute morgen [hier ](https://github.com/robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland/issues/29#issuecomment-2309518891) ein kurzes Update gegeben.
Wir können aktuell leider noch nicht einschätzen, wann die Probleme behoben sein werden. Wir melden uns, sobald wir mehr Informationen haben.
Viele Grüße
RKI Open Data Team

**Comment by RKIOpenData** [comment]
Liebe Nutzer:innen, 
leider können wir aufgrund von Urlaubs- und Krankheitsausfällen die Daten erst ab nächster Woche wieder zur Verfügung stellen.
Viele Grüße
RKI Open Data Team

**Comment by HorstErnst** [comment]
Heute wurden die Daten nachgereicht, hier ist es wieder aktuell.

**Comment by RKIOpenData** [comment]
Liebe Nutzer:innen,
jetzt nochmal ein kurzes Update von uns: Wir konnten nun einige Daten (für [COVID-19_7-Tage-Inzidenz_in_Deutschland](https://github.com/robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland) und für [COVID-19-Hospitalisierungen_in_Deutschland](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland)) nun doch früher als erwartet wieder zur Verfügung stellen.
Die Daten für dieses Repo ([COVID-19-Todesfaelle_in_Deutschland](https://github.com/robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland)) sind bislang nur teilweise up-to-date. Wir arbeiten daran, das zu beheben.
Viele Grüße
RKI Open Data Team
