### ISSUE TITLE
Update 10.09.24 fehlt

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#25]
Ebenso bei COVID-19_7-Tage-Inzidenz_in_Deutschland

**Comment by RKIOpenData** [comment]
Hallo,
die Daten für heute sind nun verfügbar, vielen Dank fürs Melden.
Noch ein kurzer Hinweis: Wir haben ein internes Monitoring für die Datenbereitstellung, insofern ist es normalerweise ausreichend, uns erst dann Bescheid zu geben, wenn die Daten länger als 12 Stunden nicht verfügbar sind. Davor ist es nicht zwingend nötig, da wir uns normalerweise zeitnah um aufkommende Probleme kümmern.
Danke und herzliche Grüße
Simon | RKI Open Data Team
