### ISSUE TITLE
Derzeit keine Updates

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#27]

**Comment by SimonScholler** [comment]
Hallo,

leider nein, Ich gebe Bescheid, sobald die Daten wieder vorliegen.

Viele Grüße
Simon | RKI Open Data Team

**Comment by Anna-Lyst** [comment]
auch heute, 23.10. fehlen die Daten ... leider "noch"(?)

Wäre fein, wenn 'wir' hier Bescheid bekommen werden/würden ... Viel **Dank** für Euere Mühen des vollständigen Nachtragens schon jetzt! :)
.

**Comment by SimonScholler** [comment]
Hallo @Anna-Lyst,

ja die Daten fehlen leider weiterhin und wir melden uns sobald die Daten wieder verfügbar sind.
Eine Frage (auch an @HorstErnst / generell an alle) bzgl. deines Hinweises: Fändest du/ihr es wichtig, dass wir proaktiv ein Issue einstellen bei fehlenden Daten? 

Danke und viele Grüße
Simon | RKI Open Data Team

**Comment by Anna-Lyst** [comment]
Antwort von mir auf Simons Frage:
sehr hilfreich wäre, von von Seiten RKI tatsächlich 'proaktiv' ein Hinweis käme / ein Issue erstellt würde, _"wenn etwas hakt"_ - also RKI-seitig Probleme in Euerem Ablauf erkennbar werden.

Denn: dann wüßten hier wenigstens alle Bescheid - und hier holen sich doch noch eine ganze Menge Leute "die Daten", die eben zum weiterhin Auswerten der Corona-Situation 'da draußen' notwendig sind (in Kombination dann mit AMELAG und ITS).

Entsprechend: wenn Ihr bemerkt, da läuft was in der Daten-Verarbeitung nicht so wie's soll, da hakt es irgendwo - gebt uns doch bitte hier (und in den anderen betroffenen Repositories !) bitte einen **klaren Hinweis** darauf.
Transparenz wäre immer toll ... heißt ja schließlich "Open Data" :)
**Danke !!**

**Comment by SimonScholler** [comment]
Liebe @Anna-Lyst, lieber @HorstErnst,

vielen herzlichen Dank für eure Rückmeldungen. Wir können die die Rückmeldung insgesamt sehr gut nachvollziehen.
Hier ein paar Punkte von uns (#Transparenz):

- Die Idee, bei Problemen automatisch ein Issue zu erstellen hatten wir ebenfalls und es ist prototypisch bereits umgesetzt. Aktuell fehlen uns aber leider die Entwickler:innenkapazitäten um es in unsere Verarbeitungspipeline aufzunehmen. Unser Ziel ist es jedoch, das so bald wie möglich umzusetzen.

- Das manuelle Anlegen eines Issues ist prinzipiell möglich und wir werden das öfter versuchen, da wir aber ein sehr kleines Team von derzeit <1.5 Personen sind, ist es nicht immer zeitnah möglich.

- Zum Punkt "Ein Hinweis wäre gut, wann wieder mit den Daten gerechnet werden kann": Dies werden wir auf absehbare Zeit leider so nicht umsetzen können. Wir bekommen die Daten oft von bundesweiten Surveillance-Systemen, die in verschiedenen anderen Abteilungen in das finale Format überführt werden und von verschiedenen technischen Infrastrukturen abhängig sind. Fehler bei einer dieser Infrastrukturen führt dann zum Ausfall der Datenaktualisierung und wir haben oft selbst sehr wenig oder keine Informationen bei Ausfall eines Systems. Wir sind dann bestrebt, das Problem zeitnah zu klären, aufgrund der vielfältigen Abhängigkeiten kann das in Einzelfällen (wie auch im aktuellen Fall hier) aber auch mal mehrere Tage dauern.

Viele Grüße
Simon | RKI Open Data Team

**Comment by HorstErnst** [comment]
Vielen Dank für diese Erläuterungen. Schade, aber es ist wohl wie es ist.

**Comment by Rutger265** [comment]
Danke für die Erklärung. Dass die IT bei euch skandalös unterbesetzt ist, war ja schon zu Spahn/Wielers Zeiten ein Problem. Es scheint sich ja noch verschärft zu haben.

Gruß, Rutger

**Comment by HannesWuensche** [comment]
Liebe Alle, 

hier ein proaktiver Hinweis: Heute gibt es leider Ausfälle bei mehreren Datensätzen. 
Wahrscheinlich lässt sich des Problem erst am Montag beheben.

Wir bedauern die Probleme sehr.

Mit besten Grüßen
@HannesWuensche 
für das Team | RKI Open Data

**Comment by SimonScholler** [comment]
Liebe Nutzer:innen,

die Datenbereitstellung klappt nun wieder.

Viele Grüße
Simon | RKI Open Data Team

**Comment by Rutger265** [comment]
Vielen Dank,RutgerAm 29.10.2024 09:25 schrieb Simon Scholler ***@***.***>:
Liebe Nutzer:innen,
die Datenbereitstellung klappt nun wieder.
Viele Grüße
Simon | RKI Open Data Team
