### ISSUE TITLE
Update is missing again (28/07/23)

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#4]

**Comment by RKIOpenData** [comment]
Hallo @Rutger265 ,

thanks for opening the issue. Unfortunately we had some technical problems providing the data. We just uploaded an up to date version from today. If there is still something missing feel free to reopen this issue.

Best regards
Knut Perseke
for the RKI Open Data Team
