### ISSUE TITLE
Update 23-08-25 fehlt!

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/COVID-19-Todesfaelle_in_Deutschland#8]

**Comment by HannesWuensche** [comment]
Liebe User,

heute gibt es leider ein Problem mit den SurvNet Daten. Wir arbeiten an einer Lösung. 
Siehe: https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/issues/8

Mit Besten Grüßen
@HannesWuensche 
für as Team RKI | Open Dat

**Comment by RKIOpenData** [comment]
Liebe User,

wir haben die Probleme bei der Datenbereitstellung behoben. Die Daten sind jetzt wieder auf dem aktuellen Stand.

mit besten Grüßen
Knut Perseke
für das Team RKI | Open Data
